version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-docker
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: voterzdb
      MYSQL_USER: voterzuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - springboot-mysql-net

  springboot-app:
    image: voterz-image
    container_name: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge
