[variables]
JAVA_VERSION = "21"

[phases.setup]
nixpkgsArchive = "23.11"

[phases.install]
cmds = ["./mvnw clean install -DskipTests"]

[phases.start]
cmd = "java -jar target/voterz-0.0.1-SNAPSHOT.jar"
